// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gicmtijvsqejdkxxiopc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpY210aWp2c3FlamRreHhpb3BjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NjQ0MDYsImV4cCI6MjA1OTQ0MDQwNn0.eTam9yNQtHn0ltkFkADNwjIlPEFSDAj-IsHP_9VeXec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
supabase
  .from('information' as any)   // ← any 캐스트
  .select('id')
  .limit(1)
  .then(...)